### ISSUE TITLE
Show a line between classes that use each other

### ISSUE THREAD

**Issue by koengabriels** [llaville/umlwriter#15]
Not sure if this applies to the current rc version but when testing with the stable version I noticed that the generated output did not show the arguments for the constructor.

We have a lot of type hinted arguments for dependency injection so I was also wondering if it is possible to have the generated UML show a line between classes that use other classes?

If this is not possible in the current RC version, is this something I could help with?
I think it would be very useful for other people as well.

**Comment by llaville** [comment]
Version 1.3 (latest stable on my branch master) does not support all PHP 7 features. 
This is the main reason, i've rewrote a new major version 2.0 that use https://github.com/goaop/parser-reflection instead of https://github.com/llaville/php-reflect

Thanks for reporting, but it does not affect v2.0

**Comment by llaville** [comment]
- Version 1.3 is now unmaintained ! 
- Current version 2.0.0 that support PHP 7 is actively maintained
- Future version 3.0.0 that support PHP 8 will come shortly now. Migration to `roave/better-reflection` v5 is done (see commit 0f56ddd)

Open a new issue report, if you found any problem with v2.0.0 and future v3.0.0
